# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  ignore:
    # ignore Java 8+ dependencies
    - dependency-name: org.mockito:mockito-core
      versions:
        - ">= 3.0"
    - dependency-name: org.apache.commons:commons-lang3
      versions:
        - ">= 3.9"
    - dependency-name: commons-io:commons-io
      versions:
        - ">= 2.7"
    # Ignore Maven 3.2.1+
    - dependency-name: org.apache.maven.plugin-testing:maven-plugin-testing-tools
      versions:
        - ">=3.2.0"
    - dependency-name: org.apache.maven.plugin-testing:maven-plugin-testing-harness
      versions:
        - ">=3.2.0"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
